services:
  api:
    container_name: api
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SAMPLE_DB
      - MYSQL_USER=root

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/api/swagger.yaml
    volumes:
      - ./api:/api

  db:
    container_name: db
    build: ./db
    volumes:
      - ./db/source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
