services:
  api:
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile.local
  db:
    build: ./db
    volumes:
      - ./db/source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
