swagger: "2.0"
info:
  title: "Go Dev Sample API"
  version: "1.0.0"
host: "localhost:8080"
basePath: "/v1"
tags:
- name: "users"
  description: "User management"
schemes:
- "http"
paths:
  /users:
    get:
      tags:
        - "users"
      summary: "Get all users"
      operationId: "getAllUsers"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "./definitions/user.yaml#/UserList"
    post:
      tags:
        - "users"
      summary: "Create user"
      operationId: "createUser"
      parameters:
        - name: "user"
          in: "body"
          required: true
          schema:
            $ref: "./definitions/user.yaml#/UserCreateRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "./definitions/user.yaml#/User"
  /users/{id}:
    get:
      tags:
        - "users"
      summary: "Get user by ID"
      operationId: "getUserByID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "./definitions/user.yaml#/User"